name: Scala CI

on:
  push:
    branches: [ "main", "testo" ]
  pull_request:
    branches: [ "main", "testo" ]


permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: 'sbt'

      - name: compile
        run: sbt compile

      - name: run tests
        run: sbt test

  test-coverage:
    name: Test

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'corretto'
          cache: 'sbt'
      - name: Run Tests
        run: sbt clean coverage test
      - name: Upload Coverage Report
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: sbt coverageReport coveralls